if not loadStatFile then
	dofile("statdesc.lua")
end
loadStatFile("stat_descriptions.txt")

local out = io.open("../Data/3_0/ModFossil.lua", "w")
out:write('-- This file is automatically generated, do not edit!\n')
out:write('-- Item data (c) Grinding Gear Games\n\nreturn {\n')
for fossil in dat"DelveCraftingModifiers":Rows() do
	if fossil.ItemType.Name ~= "Tangled Fossil" then
		for _, mod in ipairs(fossil.FossilMods) do
			out:write('\t{ ')
			if mod.GenerationType == 1 then
				out:write('type = "Prefix", ')
			elseif mod.GenerationType == 2 then
				out:write('type = "Suffix", ')
			end
			out:write('affix = "', mod.Name, '", ')
			local stats, orders = describeMod(mod)
			out:write('"', table.concat(stats, '", "'), '", ')
			out:write('statOrder = { ', table.concat(orders, ', '), ' }, ')
			out:write('level = ', mod.Level, ', group = "', mod.Family, '", ')
			out:write('types = {')
			for i, tag in ipairs(mod.SpawnTags) do
				if mod.SpawnWeights[i] > 0 then
					out:write('"', tag.Id, '", ')
				end
			end
			out:write('}, modTypeTags = {')
			for _, class in ipairs(mod.Type.Tags) do
				out:write('["', class.Id, '"] = true, ')
			end
			out:write('}, fossil = "', fossil.ItemType.Name, '", ')
			out:write('},\n')
		end
	end
end

out:write('}')
out:close()

print("Fossil mods exported.")